blank_issues_enabled: true
contact_links:
  - name: 文档
    url: https://b.2024666.xyz/
    about: 仔细阅读文档
  - name: 文档（备用）
    url: https://bilioutils.js.org/
    about: 仔细阅读文档
  - name: 其他联系方式
    url: https://b.2024666.xyz/about.html
    about: 希望能够在Github之外联系
  - name: 说点什么
    url: https://github.com/catlair/BiliOutils/discussions
    about: 如果您不是反馈问题，只是单纯聊聊，请使用 discussions 频道
