import type { TaskCombineDto } from './big-point.dto';

export const defStatus = {
  vip_info: {
    type: 2,
    status: 1,
    due_date: 1740240000000,
    vip_pay_type: 0,
    label: {
      path: 'http://i0.hdslb.com/bfs/vip/label_annual.png',
      text_color: '',
      bg_style: 0,
      bg_color: '',
      border_color: '',
      use_img_label: false,
      img_label_uri_hans: '',
      img_label_uri_hant: '',
      img_label_uri_hans_static: '',
      img_label_uri_hant_static: '',
    },
    start_time: 1572712241,
    paid_type: 0,
    mid: 10086,
    role: 3,
    tv_vip_status: 0,
    tv_vip_pay_type: 0,
    tv_due_date: 1655827200,
  },
  point_info: {
    point: 99999,
    expire_point: 0,
    expire_time: 1693497599,
    expire_days: 1,
  },
  task_info: {
    modules: [
      {
        module_title: '福利任务',
        common_task_item: [
          {
            task_code: 'bonus',
            state: 1,
            title: '大会员福利大积分',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20220607/b66bfe4ccfd6bed05bdb54008ff5c7aa/IbtMl6R3yt.png',
            subtitle: '大会员/年度大会员<br /><span class="active">+100/200大积分',
            explain:
              '在期大会员可领取100大积分，在期年度大会员可领取200大积分，每人限领1次。如当身份为大会员时已领取过本任务大积分，则后续成为年度大会员也无法补领取差值大积分。',
            vip_limit: 1,
            complete_times: 0,
            max_times: 1,
            recall_num: 0,
          },
          {
            task_code: 'dress-up',
            state: 1,
            title: '使用免费体验装扮权益',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20230316/b66bfe4ccfd6bed05bdb54008ff5c7aa/d8FFfwIwFC.png',
            subtitle: '<span class="active">+50大积分</span>',
            explain:
              '任务周期内使用大会员“免费体验装扮”权益，佩戴任意体验装扮1次可得50大积分，每人限完成1次。',
            link: 'https://www.bilibili.com/h5/mall/home?navhide=1&f_source=vip&from=vipzx.shop',
            vip_limit: 1,
            complete_times: 0,
            max_times: 1,
            recall_num: 0,
          },
        ],
      },
      {
        module_title: '体验任务',
        common_task_item: [
          {
            task_code: 'privilege',
            state: 1,
            title: '浏览大会员权益页面',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20220607/b66bfe4ccfd6bed05bdb54008ff5c7aa/IbtMl6R3yt.png',
            subtitle: '<span class="active">+50大积分</span>',
            explain: '从本任务入口跳转至大会员权益页，浏览后可得50大积分，每人限完成1次。',
            link: 'https://big.bilibili.com/mobile/rights?closable=1&navhide=1',
            vip_limit: 0,
            complete_times: 1,
            max_times: 1,
            recall_num: 0,
          },
        ],
      },
      {
        module_title: '日常任务',
        module_sub_title: '截止至08-30 23:59:59',
        common_task_item: [
          {
            task_code: 'dress-view',
            state: 1,
            title: '浏览装扮商城主页',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20230316/b66bfe4ccfd6bed05bdb54008ff5c7aa/d8FFfwIwFC.png',
            subtitle: '<span class="active">+10大积分</span>',
            explain: '从本任务入口跳转至装扮商城主页即可完成任务，每人限完成1次。',
            link: 'https://www.bilibili.com/h5/mall/home?f_source=vip&navhide=1',
            vip_limit: 1,
            complete_times: 0,
            max_times: 1,
            recall_num: 0,
          },
          {
            task_code: 'vipmallview',
            state: 1,
            title: '浏览会员购页面10秒',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20220613/b66bfe4ccfd6bed05bdb54008ff5c7aa/RnlARrUdOY.png',
            subtitle: '<span class="active">+10大积分</span>',
            explain:
              '从本任务入口跳转至会员购页面，并连续浏览页面达10秒可得10大积分，每天可完成1次。如浏览过程中离开会员购页面则中断计时，任务判定失败，需重新从本任务入口再次跳转。',
            link: 'bilibili://mall/home?msource=member_integral_browse&action=browse_all&eventId=hevent_oy4b7h3epeb&eventTime=10&showCountDown=2&taskName1=%E6%B5%8F%E8%A7%8810%E7%A7%92&taskName1Placeholder=%E6%B5%8F%E8%A7%88%25ss&taskName2=%E5%BE%97%E7%A7%AF%E5%88%86&taskEndText=%E4%BB%BB%E5%8A%A1%E5%AE%8C%E6%88%90',
            vip_limit: 1,
            complete_times: 0,
            max_times: 1,
            recall_num: 0,
          },
          {
            task_code: 'vipmallbuy',
            state: 1,
            title: '购买指定会员购商品',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20220613/b66bfe4ccfd6bed05bdb54008ff5c7aa/RnlARrUdOY.png',
            subtitle: '实付1元<span class="active">+10大积分</span>，当前0/2000',
            explain:
              '领取本任务后，当天内购买会员购商品的首笔订单（除魔力赏/一番赏/票务/先行预定订单外）可获得大积分，每实付1元+10大积分，每天上限2000大积分。本任务不支持先行购买后补领取大积分。如用户通过购买会员购商品获得了本任务大积分，后续将购买的商品退款，则同时会扣除当时获得的任务大积分。如购买商品获得大积分后的当天内产生退款，则大积分扣除后，当天无法再完成此任务。',
            link: 'bilibili://mall/home?msource=member_integral_buy',
            vip_limit: 1,
            complete_times: 0,
            max_times: 20000,
            recall_num: 0,
          },
          {
            task_code: 'animatetab',
            state: 1,
            title: '浏览追番频道页10秒',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20220607/b66bfe4ccfd6bed05bdb54008ff5c7aa/uOwc1tuJwm.png',
            subtitle: '<span class="active">+10大积分</span>',
            explain:
              '从本任务入口跳转至追番频道页，并连续浏览页面达10秒可得10大积分，每天可完成1次。如浏览过程中离开追番频道页则中断计时，任务判定失败，需重新从本任务入口再次跳转。',
            link: 'bilibili://home?bottom_tab_name=首页&tab_name=追番&tab_id=bangumi&vip_task_countdown=10000',
            vip_limit: 1,
            complete_times: 0,
            max_times: 1,
            recall_num: 0,
          },
          {
            task_code: 'ogvwatch',
            state: 1,
            title: '观看任意正片内容',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20220607/b66bfe4ccfd6bed05bdb54008ff5c7aa/6prGo240Md.png',
            subtitle: '每观看15分钟<span class="active">+20大积分</span>',
            explain:
              '领取本任务后，当天内观看番剧/国创/电影/电视剧/综艺/纪录片任意品类的正片内容的累计时长每达到15分钟可得20大积分，每天上限40大积分。单次观看行为需大于15秒才会被记入当天累计观看时长中。',
            link: 'https://www.bilibili.com/blackboard/activity-NUbGzdNJpz.html?msource=jifen',
            vip_limit: 1,
            complete_times: 0,
            max_times: 2,
            recall_num: 0,
          },
          {
            task_code: 'tvodbuy',
            state: 1,
            title: '购买单点付费影片',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20220607/b66bfe4ccfd6bed05bdb54008ff5c7aa/6prGo240Md.png',
            subtitle: '会员特价/独家付费任意影片<br /><span class="active">+70大积分</span>',
            explain:
              '领取本任务后，当天内购买任意1部会员特价/独家付费的影片可得70大积分，每天上限70大积分。',
            link: 'https://www.bilibili.com/blackboard/activity-F6sCMq4w92.html?msource=jifen',
            vip_limit: 1,
            complete_times: 0,
            max_times: 1,
            recall_num: 0,
          },
          {
            task_code: 'dressbuyamount',
            state: 1,
            title: '购买指定装扮商品',
            icon: 'https://i0.hdslb.com/bfs/activity-plat/static/20230316/b66bfe4ccfd6bed05bdb54008ff5c7aa/d8FFfwIwFC.png',
            subtitle: '实付1元<span class="active">+10大积分</span>，当前0/1000',
            explain:
              '领取本任务后，当天内购买装扮商城商品的订单（除装扮赏/祈愿/数字藏品订单外）可获得大积分，每实付1元+10大积分，每天上限1000大积分。本任务不支持先行购买后补领取大积分。',
            link: 'https://www.bilibili.com/h5/mall/home?navhide=1&f_source=vip&from=vipzx.shop',
            vip_limit: 1,
            complete_times: 0,
            max_times: 10000,
            recall_num: 0,
          },
        ],
      },
    ],
    sing_task_item: {
      histories: [
        {
          day: '2023-08-24',
          signed: true,
          score: 5,
        },
      ],
      count: 236,
      base_score: 5,
    },
    score_month: 2330,
    score_limit: 10000,
  },
  current_ts: 1693397004,
  integration_task: false,
} as TaskCombineDto['data'];
