name: build-docker

on:
  workflow_dispatch:
    inputs:
      beta:
        description: '是否使用 beta 版本'
        required: true
        default: 'true'
      tag:
        description: 'tag'
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set Docker tag
        run: |
          sed -i 2a\echo\ version=${{ github.event.inputs.tag }} docker-entrypoint.sh
          echo ${{ github.event.inputs.tag }} >> src/version.txt
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ secrets.DOCKER_PLATFORMS || 'linux/amd64,linux/arm64/v8' }}
          tags: catlair/bilioutils:${{ github.event.inputs.beta == 'true' && 'dev' || 'latest' }},catlair/bilioutils:${{ github.event.inputs.tag }}
