name: build-npm-docker

on:
  workflow_dispatch:
    inputs:
      beta:
        description: '是否使用 beta 版本'
        required: true
        default: 'true'
      tag:
        description: 'tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    env:
      IS_BETA: ${{ github.event.inputs.beta == 'true' }}
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          rm yarn.lock
          cat package.json | jq "del( .optionalDependencies ) | .version = \"${{ github.event.inputs.tag }}\"" > temp.json
          mv temp.json package.json
          yarn install
          rm yarn.lock
      - name: Build and Handle
        run: |
          yarn build
      - run: npm publish ${{ env.IS_BETA == 'true' && '--tag beta' || '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  build-docker:
    runs-on: ubuntu-latest
    needs: build
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set Docker tag
        run: |
          sed -i 2a\echo\ version=${{ github.event.inputs.tag }} docker-entrypoint.sh
          echo ${{ github.event.inputs.tag }} >> src/version.txt
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ secrets.DOCKER_PLATFORMS || 'linux/amd64,linux/arm64/v8' }}
          tags: catlair/bilioutils:${{ github.event.inputs.beta == 'true' && 'dev' || 'latest' }},catlair/bilioutils:${{ github.event.inputs.tag }}
